# site
#theme : minima
theme : jekyll-theme-minimal
title : tofmemo
description : Tower of Fantasy Memo

# sicual links
twitter_username : BanxTera
github_username : banx-jp
author : Banx
email : hogehoge@gmail.com
url : https://banx-jp.github.io/tofmemo/

# navigation links
header_pages :
  - index.md
  - doc/exclusive.md
  - doc/jointoperation.md
  - doc/unmannedhunting.md
